# syntax=docker/dockerfile:1
# check=skip=UndefinedVar

FROM mcr.microsoft.com/dotnet/aspnet:9.0-noble@sha256:088655e4b9bd41d72e9f6d3ba96af5f556b217bf8cac7f26b002a27db0693530 AS base

# Force apt-get to not use TTY
ENV DEBIAN_FRONTEND=noninteractive

# Configure local user
ENV USER=root
ENV HOME=/app-root

# Avoid Python cache during build
ENV PYTHONDONTWRITEBYTECODE=1

# Allow install Python system packages
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Install:
# - Azure CLI system requirements (C/Rust build tools for libs non pre-built on this platform)
# - Azure Pipelines agent system requirements
# - dbus-user-session, fuse-overlayfs, iptables, for BuildKit
# - gzip, make, tar, unzip, wget, zip, zstd, dnsutils, rsync, for developer ease-of-life
# - zsh, for inter-operability
RUN rm -f /etc/apt/apt.conf.d/docker-clean \
    && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=target=/var/lib/apt/lists,type=cache,id=apt-lists-${TARGETPLATFORM},sharing=locked --mount=target=/var/cache,type=cache,id=var-cache-${TARGETPLATFORM},sharing=locked \
    apt-get update -q \
    && apt-get install -y -q --no-install-recommends \
        build-essential \
        ca-certificates \
        cargo \
        curl \
        dbus-user-session \
        dnsutils \
        fuse-overlayfs \
        git \
        git-lfs \
        gnupg \
        gzip \
        iptables \
        iputils-ping \
        jq \
        libffi-dev \
        libssl-dev \
        lsb-release \
        make \
        pkg-config \
        rsync \
        software-properties-common \
        sudo \
        tar \
        uidmap \
        unzip \
        wget \
        zip \
        zsh \
        zstd \
    && find / -depth -type d -name __pycache__ -exec rm -rf {} \; 2> /dev/null

# Copy helper script, then verify installation
COPY arch.sh .
RUN chmod +x arch.sh \
    && bash arch.sh

# Persist Python version
ARG PYTHON_VERSION_MAJOR_MINOR
ARG PYTHON_VERSION_PATCH
ENV PYTHON_VERSION=${PYTHON_VERSION_MAJOR_MINOR}.${PYTHON_VERSION_PATCH}

FROM base AS rootlesskit

# Install Go, then verify installation
ARG GO_VERSION
ENV GO_VERSION=${GO_VERSION}
RUN rm -rf /usr/local/go \
    && curl -LsSf --retry 8 --retry-all-errors https://go.dev/dl/go${GO_VERSION}.linux-$(ARCH_X64=amd64 bash arch.sh).tar.gz | tar -xz -C /usr/local
ENV PATH="${PATH}:/usr/local/go/bin"
RUN go version

# Install RootlessKit, then verify installation
ARG ROOTLESSKIT_VERSION
ENV ROOTLESSKIT_VERSION=${ROOTLESSKIT_VERSION}
RUN --mount=target=/rootlesskit-${ROOTLESSKIT_VERSION},type=cache,id=rootlesskit-${ROOTLESSKIT_VERSION}-${TARGETPLATFORM},sharing=locked \
    git clone --depth 1 --branch v${ROOTLESSKIT_VERSION} https://github.com/rootless-containers/rootlesskit.git rootlesskit \
    # Ugly but that's work
    && cp -r rootlesskit/* rootlesskit-${ROOTLESSKIT_VERSION} \
    && rm -rf rootlesskit \
    && cd rootlesskit-${ROOTLESSKIT_VERSION} \
    && make \
    && make install \
    && cd .. \
    && rootlesskit --version \
    && rootlessctl --version

FROM base AS python

# Build Python from source, then verify installation
RUN --mount=target=/var/lib/apt/lists,type=cache,id=apt-lists-${TARGETPLATFORM},sharing=locked --mount=target=/var/cache,type=cache,id=var-cache-${TARGETPLATFORM},sharing=locked --mount=target=/Python-${PYTHON_VERSION},type=cache,id=python-${PYTHON_VERSION}-${TARGETPLATFORM},sharing=locked \
    apt-get update -q \
    && apt-get install -y -q --no-install-recommends \
        g++ \
        lcov \
        libbz2-dev \
        libgdbm-compat-dev \
        libgdbm-dev \
        liblzma-dev  \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libreadline6-dev \
        libsqlite3-dev \
        libxml2-dev \
        libxmlsec1-dev \
        lzma \
        lzma-dev \
        uuid-dev \
        xz-utils \
        zlib1g-dev \
    && curl -LsSf --retry 8 --retry-all-errors https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz -o python.tgz \
    && tar -xzf python.tgz \
    && rm python.tgz \
    && cd Python-${PYTHON_VERSION} \
    && gnu_arch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
    && ./configure \
        --build=$gnu_arch \
        --enable-optimizations \
        --with-ensurepip=install \
        --with-lto \
    && make profile-removal \
    && extra_cflags="$(dpkg-buildflags --get CFLAGS)" \
    && ldflags="$(dpkg-buildflags --get LDFLAGS)" \
    && make -j $(nproc) "EXTRA_CFLAGS=${extra_cflags:-}" "LDFLAGS=${ldflags:-}" \
    && make install \
    && cd .. \
    && python3 --version \
    && python3 -m pip --version \
    && find / -depth -type d -name __pycache__ -exec rm -rf {} \; 2> /dev/null

FROM base

# Install Python, then verify installation
COPY --from=python /usr/local/bin/python${PYTHON_VERSION_MAJOR_MINOR} /usr/local/bin/python${PYTHON_VERSION_MAJOR_MINOR}
COPY --from=python /usr/local/lib/python${PYTHON_VERSION_MAJOR_MINOR} /usr/local/lib/python${PYTHON_VERSION_MAJOR_MINOR}
RUN ln -s /usr/local/bin/python${PYTHON_VERSION_MAJOR_MINOR} /usr/local/bin/python3 \
    && ln -s /usr/local/bin/python${PYTHON_VERSION_MAJOR_MINOR} /usr/local/bin/python \
    && python --version \
    && python3 --version \
    && python${PYTHON_VERSION_MAJOR_MINOR} --version \
    && python3 -m pip --version

# Install Python build tools
RUN --mount=target=/${USER}/.cache/pip,type=cache,id=pip-${PYTHON_VERSION_MAJOR_MINOR}-${TARGETPLATFORM},sharing=locked \
    python3 -m pip \
        --disable-pip-version-check \
        --quiet \
        --retries 8 \
        --timeout 120 \
        install \
            --upgrade \
            pip setuptools wheel \
    && find / -depth -type d -name __pycache__ -exec rm -rf {} \; 2> /dev/null

# Install Azure CLI, then verify installation
ARG AZURE_CLI_VERSION
ENV AZURE_CLI_VERSION=${AZURE_CLI_VERSION}
RUN --mount=target=/${USER}/.cache/pip,type=cache,id=pip-${PYTHON_VERSION_MAJOR_MINOR}-${TARGETPLATFORM},sharing=locked \
    python3 -m pip \
        --disable-pip-version-check \
        --quiet \
        --retries 8 \
        --timeout 120 \
        install \
            azure-cli==${AZURE_CLI_VERSION} \
    && az version \
    && rm -rf ${HOME}/.azure ${HOME}/.cache/pip \
    && find / -depth -type d -name __pycache__ -exec rm -rf {} \; 2> /dev/null

# Install AWS CLI, then verify installation
ARG AWS_CLI_VERSION
ENV AWS_CLI_VERSION=${AWS_CLI_VERSION}
RUN curl -LsSf --retry 8 --retry-all-errors https://awscli.amazonaws.com/awscli-exe-linux-$(ARCH_X64=x86_64 ARCH_ARM64=aarch64 bash arch.sh)-${AWS_CLI_VERSION}.zip -o awscli.zip \
    && unzip -q awscli.zip \
    && ./aws/install \
    && rm -rf awscli.zip aws \
    && aws --version

# Install Google Cloud CLI, then verify installation
ARG GCLOUD_CLI_VERSION
ENV GCLOUD_CLI_VERSION=${GCLOUD_CLI_VERSION}
RUN curl -LsSf --retry 8 --retry-all-errors https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${GCLOUD_CLI_VERSION}-linux-$(ARCH_X64=x86_64 ARCH_ARM64=arm bash arch.sh).tar.gz | tar -xz -C /usr/local \
    && /usr/local/google-cloud-sdk/install.sh \
        --additional-components beta \
        --quiet \
    && ln -s /usr/local/google-cloud-sdk/bin/gcloud /usr/bin/gcloud \
    && ln -s /usr/local/google-cloud-sdk/bin/gsutil /usr/bin/gsutil \
    && gcloud version \
    && rm -rf /usr/local/google-cloud-sdk/.install ${HOME}/.config/gcloud \
    && find / -depth -type d -name __pycache__ -exec rm -rf {} \; 2> /dev/null

# Install Powershell, then verify installation
ARG POWERSHELL_VERSION
ENV POWERSHELL_VERSION=${POWERSHELL_VERSION}
RUN mkdir -p /opt/microsoft/powershell \
    && curl -LsSf --retry 8 --retry-all-errors https://github.com/PowerShell/PowerShell/releases/download/v${POWERSHELL_VERSION}/powershell-${POWERSHELL_VERSION}-linux-$(bash arch.sh).tar.gz | tar -xz -C /opt/microsoft/powershell \
    && chmod +x /opt/microsoft/powershell/pwsh \
    && ln -s /opt/microsoft/powershell/pwsh /usr/bin/pwsh \
    && pwsh -Version \
    && rm -rf ${HOME}/.config/powershell ${HOME}/.cache/powershell

# Install YQ, then verify installation
ARG YQ_VERSION
ENV YQ_VERSION=${YQ_VERSION}
RUN curl -LsSf --retry 8 --retry-all-errors https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_$(ARCH_X64=amd64 bash arch.sh) -o /usr/bin/yq \
    && chmod +x /usr/bin/yq \
    && yq --version

# Install Tini, then verify installation
ARG TINI_VERSION
ENV TINI_VERSION=${TINI_VERSION}
RUN curl -LsSf --retry 8 --retry-all-errors https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-$(ARCH_X64=amd64 bash arch.sh) -o /tini \
    && chmod +x /tini \
    && /tini --version
ENTRYPOINT ["/tini", "--"]

# Install BuildKit, then verify installation
ARG BUILDKIT_VERSION
ENV BUILDKIT_VERSION=${BUILDKIT_VERSION}
RUN mkdir buildkit \
    && curl -LsSf --retry 8 --retry-all-errors https://github.com/moby/buildkit/releases/download/v${BUILDKIT_VERSION}/buildkit-v${BUILDKIT_VERSION}.linux-$(ARCH_X64=amd64 bash arch.sh).tar.gz | tar -xz -C buildkit \
    && mv buildkit/bin/* /usr/local/bin \
    && rm -rf buildkit \
    && buildctl --version \
    && buildkitd --version

# Install RootlessKit, then verify installation
COPY --from=rootlesskit /usr/local/bin/rootless* /usr/bin/
RUN rootlesskit --version \
    && rootlessctl --version

# Install Azure Pipelines Agent sources, then verify installation
ARG AZP_AGENT_VERSION
ENV AZP_AGENT_VERSION=${AZP_AGENT_VERSION}
ENV AZP_HOME=${HOME}/azp-agent
# Disable agent auto-updates
# See: https://github.com/microsoft/azure-pipelines-agent/blob/b5ff4408239f3e938560f8b2e3848df76489a8d0/src/Agent.Listener/Agent.cs#L354C24-L354C24
ENV agent.disableupdate="1"
RUN mkdir -p ${AZP_HOME} \
    && curl -LsSf --retry 8 --retry-all-errors https://vstsagentpackage.azureedge.net/agent/${AZP_AGENT_VERSION}/pipelines-agent-linux-$(bash arch.sh)-${AZP_AGENT_VERSION}.tar.gz | tar -xz -C ${AZP_HOME} \
    && cd ${AZP_HOME} \
    && chmod +x run-docker.sh config.sh \
    && AGENT_ALLOW_RUNASROOT="1" bash run-docker.sh --version \
    && rm -rf _diag \
    # Allow local user to R/W to agent home
    && chmod -R a+w .
ENV AZP_WORK=${HOME}/azp-work
ENV AZP_CUSTOM_CERT_PEM=${HOME}/azp-custom-certs

# Cleanup helper script
RUN rm arch.sh

# Reset Python configs to default
ENV PYTHONDONTWRITEBYTECODE=
ENV PIP_BREAK_SYSTEM_PACKAGES=

# Configure local user
RUN mkdir -p /run/user/0 ${HOME}/.local/tmp ${HOME}/.local/share/buildkit \
    && chown -R ${USER} /run/user/0 ${HOME} \
    && echo ${USER}:100000:65536 | tee /etc/subuid | tee /etc/subgid
USER 0:0
ENV XDG_RUNTIME_DIR=/run/user/0
ENV TMPDIR=${HOME}/.local/tmp
ENV BUILDKIT_HOST=unix:///run/user/0/buildkit/buildkitd.sock

# Install Azure Pipelines Agent startup script
WORKDIR ${AZP_HOME}
COPY start.sh .
# Run as exec form, so that it can receive signals from Tini
CMD ["bash", "start.sh"]
