# Fetch the vendor with the builder platform to avoid QEMU issues
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:6.0-focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q
RUN apt-get upgrade -y -q --no-install-recommends

# Install:
# - Azure Pipelines agent system requirements
# - Azure CLI system requirements (Python 3.8, plus C/Rust build tools for libs non pre-built on this platform)
# - "tar, unzip, gzip, zip, zsh, zstd" for developer ease-of-life
RUN apt-get install -y -q --no-install-recommends \
    build-essential \
    ca-certificates \
    cargo \
    curl \
    git \
    gzip \
    iputils-ping \
    jq \
    libffi-dev \
    libssl-dev \
    lsb-release \
    pkg-config \
    python3-dev=3.8.* \
    python3-pip \
    python3=3.8.* \
    software-properties-common \
    tar \
    unzip \
    zip \
    zsh \
    zstd

# Install Azure CLI
RUN python3 -m pip install --no-cache-dir --upgrade pip \
    && python3 -m pip install --no-cache-dir setuptools wheel \
    && python3 -m pip install --no-cache-dir azure-cli \
    && az --version

WORKDIR /azp

COPY init.sh .
ARG AGENT_VERSION
ENV AGENT_VERSION ${AGENT_VERSION}
RUN chmod +x init.sh \
    && ./init.sh $AGENT_VERSION

COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
