FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q
RUN apt-get upgrade -y -q --no-install-recommends

# Install:
# - Azure Pipelines agent system requirements
# - "make, tar, unzip, gzip, zip, zstd" for developer ease-of-life
RUN apt-get install -y -q --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    git \
    gzip \
    iputils-ping \
    jq \
    lsb-release \
    make \
    software-properties-common \
    tar \
    unzip \
    zip \
    zstd

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /azp

COPY init.sh .
ARG AGENT_VERSION
ENV AGENT_VERSION ${AGENT_VERSION}
RUN chmod +x init.sh \
    && ./init.sh $AGENT_VERSION

COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
