# Fetch the vendor with the builder platform to avoid QEMU issues
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:6.0-focal

ENV DEBIAN_FRONTEND=noninteractive

# Install:
# - Azure Pipelines agent system requirements
# - zsh, for inter-operability
# - gzip, make, tar, unzip, wget, yq, zip, zstd for developer ease-of-life
# - Azure CLI system requirements (Python 3.8, plus C/Rust build tools for libs non pre-built on this platform)
RUN apt-get update -q \
    && apt-get install -y -q --no-install-recommends \
        build-essential \
        ca-certificates \
        cargo \
        curl \
        git \
        git-lfs \
        gnupg \
        gzip \
        iputils-ping \
        jq \
        libffi-dev \
        libssl-dev \
        lsb-release \
        make \
        pkg-config \
        python3-dev=3.8.* \
        python3-pip \
        python3=3.8.* \
        software-properties-common \
        sudo \
        tar \
        unzip \
        wget \
        zip \
        zsh \
        zstd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

# Copy helper script, then verify installation
COPY arch.sh .
RUN chmod +x arch.sh \
    && ./arch.sh

# Install Azure CLI, then verify installation
RUN python3 -m pip install --upgrade pip setuptools wheel \
    && python3 -m pip install azure-cli \
    && rm -rf $HOME/.cache/pip \
    && az --version

# Install Powershell, then verify installation
ARG POWERSHELL_VERSION
ENV POWERSHELL_VERSION ${POWERSHELL_VERSION}
RUN mkdir -p /opt/microsoft/powershell \
    && curl -LsSf https://github.com/PowerShell/PowerShell/releases/download/v${POWERSHELL_VERSION}/powershell-${POWERSHELL_VERSION}-linux-$(./arch.sh).tar.gz | tar -xz -C /opt/microsoft/powershell \
    && chmod +x /opt/microsoft/powershell/pwsh \
    && ln -s /opt/microsoft/powershell/pwsh /usr/bin/pwsh \
    && pwsh -Version

# Install Azure Pipelines Agent sources, then verify installation
ARG AGENT_VERSION
ENV AGENT_VERSION ${AGENT_VERSION}
ENV AGENT_HOME /azp
RUN mkdir -p ${AGENT_HOME} \
    && curl -LsSf https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/pipelines-agent-linux-$(./arch.sh)-${AGENT_VERSION}.tar.gz | tar -xz -C ${AGENT_HOME} \
    && cd $AGENT_HOME \
    && chmod +x ./run-docker.sh ./config.sh \
    && AGENT_ALLOW_RUNASROOT="1" ./run-docker.sh --version

# Install YQ, then verify installation
ARG YQ_VERSION
ENV YQ_VERSION ${YQ_VERSION}
RUN curl -LsSf https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_$(ARCH_AMD64=amd64 ./arch.sh) -o /usr/bin/yq \
    && chmod +x /usr/bin/yq \
    && yq --version

# Cleanup helper script
RUN rm arch.sh

# Set agent home as working directory
WORKDIR ${AGENT_HOME}

# Install Azure Pipelines Agent startup script
COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
