{{- if not (and (.Values.autoscaling.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1")) -}}
# Regular Agent Deployment (when autoscaling is disabled)
# These agents run continuously and process jobs directly
# When autoscaling is enabled, this deployment is not created and jobs are handled by ScaledJob
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blue-agent.fullname" . }}
  labels:
    {{- include "blue-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "blue-agent.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount | int | required "A value for .Values.replicaCount is required" }}
  # Force >= 1, because otherwise it will cause inability to rollback (see: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
  revisionHistoryLimit: {{ max 1 (.Values.revisionHistoryLimit | int | required "A value for .Values.revisionHistoryLimit is required") }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "blue-agent.selectorLabels" . | nindent 8 }}
      annotations:
        # Cluster autoscaler never evicts this Pod
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $data := dict
        "azpAgentName" (dict "valueFrom" (dict "fieldRef" (dict "apiVersion" "v1" "fieldPath" "metadata.name" )))
        "isTemplateJob" "0"
        "restartPolicy" "Always"
      }}
      {{- include "blue-agent.podSharedTemplate" (merge (dict "Args" $data) . ) | nindent 6 }}
{{- end }}
