{{- if and (.Values.autoscaling.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1") -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "blue-agent.fullname" . }}
  labels:
    {{- include "blue-agent.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: organizationURL
      name: {{ include "blue-agent.secretName" . }}
      key: organizationURL
    - parameter: personalAccessToken
      name: {{ include "blue-agent.secretName" . }}
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "blue-agent.fullname" . }}
  labels:
    {{- include "blue-agent.labels" . | nindent 4 }}
spec:
  # Historical jobs cleanup
  failedJobsHistoryLimit: {{ .Values.pipelines.cleanup.failed | int | required "A value for .Values.pipelines.cleanup.failed is required" }}
  successfulJobsHistoryLimit: {{ .Values.pipelines.cleanup.successful | int | required "A value for .Values.pipelines.cleanup.successful is required" }}
  # Min/max replicas
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas | int | required "A value for .Values.autoscaling.maxReplicas is required" }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas | int | required "A value for .Values.autoscaling.minReplicas is required" }}
  # Target job to scale
  jobTargetRef:
    activeDeadlineSeconds: {{ .Values.pipelines.timeout | int | required "A value for .Values.pipelines.timeout is required" }}
    backoffLimit: 0 # Do not retry
    parallelism: 1 # Only one pod at a time
    ttlSecondsAfterFinished: {{ .Values.pipelines.cleanup.ttl | int | required "A value for .Values.pipelines.cleanup.ttl is required" }}
    template:
      metadata:
        labels:
          {{- include "blue-agent.labels" . | nindent 10 }}
        annotations:
          # Cluster autoscaler never evicts this Pod
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          {{- with .Values.annotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        {{- $data := dict
          "azpAgentName" (dict "valueFrom" (dict "fieldRef" (dict "apiVersion" "v1" "fieldPath" "metadata.name" )))
          "isTemplateJob" "0"
          "restartPolicy" "Never"
        }}
        {{- include "blue-agent.podSharedTemplate" (merge (dict "Args" $data) . ) | nindent 8 }}
  # Do not delete executed jobs during upgrade
  rollout:
    strategy: gradual
  # Azure Pipelines scaler returns the number of jobs in the queue, incl the current job
  scalingStrategy:
    strategy: accurate
  # Rules to scale up/down
  pollingInterval: {{ .Values.autoscaling.pollingInterval | int | required "A value for .Values.autoscaling.pollingInterval is required" }}
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: {{ .Values.pipelines.poolName | quote | required "A value for .Values.pipelines.poolName is required" }}
        parent: {{ include "blue-agent.fullname" . }}-template
      authenticationRef:
        name: {{ include "blue-agent.fullname" . }}
{{- end }}
